export default {
  ORDER_DASHBOARD_REQUEST: 'ORDER_DASHBOARD_REQUEST',
  ORDER_MEALS_DASHBOARD_REQUEST: 'ORDER_MEALS_DASHBOARD_REQUEST',
  ORDER_DASHBOARD_FAILURE: 'ORDER_DASHBOARD_FAILURE',
  ORDER_MEALS_DASHBOARD_SUCCESS: 'ORDER_MEALS_DASHBOARD_SUCCESS',
  ORDER_MEALS_DASHBOARD_FAILURE: 'ORDER_MEALS_DASHBOARD_FAILURE',
  ORDER_DASHBOARD_HISTORY_SUCCESS: 'ORDER_DASHBOARD_HISTORY_SUCCESS',
  ORDER_DASHBOARD_HISTORY_FAILURE: 'ORDER_DASHBOARD_HISTORY_FAILURE',
  DASHBOARD_TOTAL_SUCCESS: 'DASHBOARD_TOTAL_SUCCESS',
  ORDER_DASHBOARD_TOTAL_SUCCESS: 'ORDER_DASHBOARD_TOTAL_SUCCESS',
};
