export default {
  MEALS_REQUEST: 'MEALS_REQUEST',
  ALL_MEALS_SUCCESS: 'ALL_MEALS_SUCCESS',
  MEALS_FAILURE: 'MEALS_FAILURE',

  UPDATE_MEAL_SUCCESS: 'UPDATE_MEAL_SUCCESS',
  CREATE_MEAL_SUCCESS: 'CREATE_MEAL_SUCCESS',
  DELETE_MEAL_SUCCESS: 'DELETE_MEAL_SUCCESS'
};