export default {
  ORDER_REQUEST: 'ORDER_REQUEST',
  ORDER_FAILURE: 'ORDER_FAILURE',
  GET_ORDER_MEAL_FAILURE: 'GET_ORDER_MEAL_FAILURE',
  GET_ORDER_MEAL_SUCCESS: 'GET_ORDER_MEAL_SUCCESS',
  POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS',
  GET_ORDER_ALL_SUCCESS: 'GET_ORDER_ALL_SUCCESS',
  UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS'
};
