export default {
  ORDER_REQUEST: 'ORDER_REQUEST',
  ORDER_FAILURE: 'ORDER_FAILURE',

  POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS',
  GET_ORDER_ALL_SUCCESS: 'GET_ORDER_ALL_SUCCESS',
  UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS'
};